### ISSUE TITLE
bug on disable addon

### ISSUE THREAD

**Issue by hannesdelbeke** [blender-renaissance/Info-Graphs-for-Blender#1]
addon loads fine.
but on disable the addon i get a bug

error on deregister
```
Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 423, in disable
    mod.unregister()
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Geometry_nodes_Graphs3.py", line 2176, in unregister
    del bpy.types.Scene.my_tool
AttributeError: my_tool
```

**Comment by blender-renaissance** [comment]
Hey, I have fixed the issue. There was a problem with deregistering the add-on. the updated add-on does not have this issue.

Sorry for the late reply, I have no idea how to enable notifications here. I will search for it now.
